### ISSUE TITLE
no test files found

### ISSUE THREAD

**Issue by mgross-lg** [HMS-Analytical-Software/SASUnit#21]
### Contact Details

Matthias.Gross@lgl.bwl.de

### What happened?

When the SASUNIT_PROJECTROOT directory has only subdirectories with test files (no test file in the project root directory) then sasunit found no test files.

### Version

2.1 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KLandwich** [comment]
Hi mgross-lg,

yes that is true. 

Runsasunit does not work recursively. It only checks the files in the given directory.
You need to specify one call to runsasunit for each folder containing test programs.

That's the way it currently is implemented.

Regards
Klaus

**Comment by mgross-lg** [comment]
In run_all.sas i can set %runSASUnit(i_source = %str(*)_test.sas, i_recursive=1).
Then test files in all subdirectories are found, when in the SASUNIT_PROJECTROOT directory has minumum one test file.
But nothing test files found when SASUNIT_PROJECTROOT has no test file.

Regard 
Matthias

**Comment by KLandwich** [comment]
Hi Matthias,

you are absolutely right. There is a switch for recursive scan.
As we got rid of the OS commands for searching files in the OS we missed that feature in the test cases.

Thanks for reporting and correcting me.

Regards
   Klaus
