### ISSUE TITLE
[Bug]: Missing Index.html

### ISSUE THREAD

**Issue by Daid13** [HMS-Analytical-Software/SASUnit#35]
### Contact Details

Daniel.White@ndph.ox.ac.uk

### Current Behaviour

First time user here. I have checked paths, run the english setup file and sasunit.9.4.windows.en.overwrite.full.cmd. I then open test_doc_en.html and it redirects me to a missing file, Index.html.

May well be a setup misunderstanding on my part rather than bug but couldn't see another place to bring up.

### Expected Behaviour

I expect it to redirect me to the home page of documentation and example project tests.

### Steps To Reproduce

Windows 11, SAS 9.4, SASUnit 2.1 from sourceforge.  With default config (and unzipped to the default path location). Run sasunit.setup.9.4.en.cmd and sasunit.9.4.windows.en.overwrite.full.cmd. Open test_doc_en.html

### Environment

```markdown
- OS: Windows 11
- SAS Version: 9.4
```

### Release

2.1 (Default)

### SASUnit Component

Reporting (Defect reports for the reporting output of SASUnit)

### Priority / Severeness of issue

3 - moderate

**Comment by Daid13** [comment]
Using the current github main branch rather than the release from sourceforge appears to have fixed it for me.

**Comment by KLandwich** [comment]
Hi Daniel,

welcome at SASUnit GitHub.

Yeah, that is one of the pitfalls in SASUnit.
Currently we support two flavors.
1. All files (e.g. pgms, logs, docu, datat) reside in on folder (includinh subfolders) beneath example\doc\sasunit\en
2. Files can be distributed over maultiple folders or folder trees. Then the doc will be output in example\en\doc

The setup you started creates the second layout. So you should see an index.html in example\en\doc.
The file test_dec_en.html, that you fin in example/doc points to the llocation of the first flavour.
sasunit.setup.9.4.asis.en.cmd is the respective steup script for the other layout.

Hope that helps.

Regards
   Klaus
